# Generated by Django 3.2.20 on 2024-12-22 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviting_score', models.IntegerField(blank=True, null=True)),
                ('guest_score', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b',
        ),
        migrations.RemoveField(
            model_name='team',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='team',
            name='location',
        ),
        migrations.RemoveField(
            model_name='team',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_size',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='guest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='matchmaking.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='inviting_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='inviting_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inviting_matches', to='matchmaking.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='suggested_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.team'),
        ),
        migrations.AddField(
            model_name='scoreproposition',
            name='suggesting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.team'),
        ),
        migrations.AddField(
            model_name='playerinvite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='matchmaking.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matchmaking.user'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matchmaking.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='guest_proposition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_g', to='matchmaking.scoreproposition'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_proposition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_h', to='matchmaking.scoreproposition'),
        ),
    ]
