# Generated by Django 3.2.20 on 2024-12-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_teamrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
